### ISSUE TITLE
Issue rendering the Rmd document

### ISSUE THREAD

**Issue by jessicablois** [NeotomaDB/Workshops#4]
I was unable to render the template, since the directory for winBacon is not included in the template zip file?

Error message:
Quitting from lines 267-271 (Workshop_Template_v0.1.Rmd) 
Error in setwd("winBacon_2.2/") : cannot change working directory

I think for the SVP workshop, I will just delete this section, but as a general example, I think we need to modify this.

**Comment by IceAgeEcologist** [comment]
I also can't render the template, but it doesn't seem to be linked to Bacon.  Here's the command and error message:

> render(input = "Workshop_PalEON_201608_v0.1.Rmd", output = "html_document")
> Error in render(input = "Workshop_PalEON_201608_v0.1.Rmd", output = "html_document") : 
>   argument 2 matches multiple formal arguments

**Comment by SimonGoring** [comment]
Can you try to remove the "output" bit?

**Comment by IceAgeEcologist** [comment]
That worked.  It created a docx file.  A few warning messages popped up:
Output created: Workshop_PalEON_201608_v0.1.docx
Warning messages:
1: In (function (toc = FALSE, toc_depth = 3, fig_width = 5, fig_height = 4,  :
  table of contents for word_document requires pandoc >= 1.14
2: package 'analogue' was built under R version 3.2.5 
3: package 'vegan' was built under R version 3.2.4 
4: package 'permute' was built under R version 3.2.4

**Comment by jessicablois** [comment]
The other way to solve the "output" issue is by changing "output=" to "output_format=".  That's what worked for me. (Noted in another issue tracker)

**Comment by SimonGoring** [comment]
This issue is resolved with commit https://github.com/NeotomaDB/Workshops/commit/e2177e7f0b726e4b0844d76c3290c3568a8af040.
